
const ethers = require('ethers')
const lighthouse = require('@lighthouse-web3/sdk')

const signAuthMessage0 = async (publicKey, privateKey) => {
    const provider = new ethers.JsonRpcProvider();
    const signer = new ethers.Wallet(privateKey, provider);
    const messageRequested = (await lighthouse.getAuthMessage(publicKey)).data.message;
    const signedMessage = await signer.signMessage(messageRequested);
    return signedMessage;
}

const signAuthMessage = async () => {
  const provider = new ethers.providers.Web3Provider(window.ethereum)
  const signer = provider.getSigner()
  const address = await signer.getAddress()
  const messageRequested = (await lighthouse.getAuthMessage(address)).data.message
  const signedMessage = await signer.signMessage(messageRequested)
  return ({
      signedMessage: signedMessage,
      publicKey: address
  })
}

const shareFile = async (fileCid, userAddressArray) => {
    try {
        // CID of the encrypted file that you want to share
        // CID is generated by uploading a file with encryption
        // Only the owner of the file can share it with another wallet address

        const cid = fileCid;
        // CID: Unique identifier for content on IPFS.
        const getFileInfo = await lighthouse.getFileInfo(cid);
        console.log("getFileInfo", getFileInfo);

        const receiverPublicKey = userAddressArray;

        const signedMessage = await signAuthMessage();

        console.log("signedMessage", signedMessage)

        const shareResponse = await lighthouse.shareFile(
            signedMessage.publicKey,
            receiverPublicKey,
            cid,
            signedMessage.signedMessage
        );
        // ShareFile: Lighthouse function to securely share your file.

        console.log(shareResponse);

    } catch (error) {
        console.log(error)
    }
}

module.exports = { shareFile };

/* Sample Response      
{
  data: {
    cid: 'QmXhvRaWPpEXgFzqBLkq75EcE79oghqE3pGtkmiU21LnPf',
    shareTo: [ '0xaf8dAa403ddB2b0742BfABE44214Fa8fBe69DCAB' ],
    status: 'Success'
  }
}
*/

/*
{
  data: {
    cid: 'QmTJrWjLY9ARCwxYqJwc4Zu8Dzm3fXakAgVvdtgc24X3BU',
    shareTo: [ '0xaf8dAa403ddB2b0742BfABE44214Fa8fBe69DCAB' ],
    status: 'Success'
  }
}
*/